# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sheikh Shafayet Hossain
title: Bachelor of Science - Computer Science Major
email: hossaiss@myumanitoba.ca
website: www.github.com/SheikhHossain/HOSSAISS.github.io

# Social links
twitter_username: SaditHossain
github_username:  Sheikh Hossain
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: SaditHossain
linkedin_username: Sheikh Shafayet Hossain
# pinterest_username: jekyll
youtube_username: Sadit Hossain
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Highly motivated, self-directed and organized Bachelor of Computer Science University student with experience in office tasks and customer service. Proficient in handling complex and sensitive information regarding collogues and clients. Efficient working with minimal supervision in a fast-paced team environment managing multiple priorities and multiple deadlines.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Technical Skills Section
# TechnicalSkills_title: Technical

# Technical Skills Section
# technical_Skills_title: Programming Languages
technical_Skils_title: | # this will include new lines to allow paragraphs
  - Python
  - Java
  - C & C++
  - HTML, CSS and JavaScript
  - Node.js
 
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
