# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sheikh Shafayet Hossain
title: Bachelor of Science - Computer Science Major
email: hossaiss@myumanitoba.ca
website: www.github.com/SheikhHossain/HOSSAISS.github.io

# Social links
twitter_username: sadithossain
github_username:  Sheikh Hossain
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sadit_hossain
linkedin_username: sheikh-shafayet-hossain
# pinterest_username: jekyll
youtube_username: Sadit Hossain
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I am Sheikh Shafayet Hossain I am a computer science graduate from the University of Manitoba. I am highly organized and detail oriented about my field of work and my life. I have had experience handling clients and their expectations. I have helped stakeholders resolve their concerns by providing tailored solutions to them.  I am proficient in handling complex and sensitive information regarding college and clients. I have worked in a fast paced team managing multiple priorities and multiple deadlines with minimal supervision. I learn best with hands on experience, hence I have worked on a few personal projects while working on my school required projects.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: whatever

# Education Section
# educaton_title: whatever


# Technical Skills
more_title: Technical Skills
more_content: | # this will include new lines to allow paragraphs
  Programming Langauges:
   - Python
   - C & C++
   - HTML, CSS & JavaScript
   - Node.js
   - Godot
   - LC3
   - Java
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 
